### ISSUE TITLE
Add Prerequisite for Installing the IBM Containers CLI Plugin

### ISSUE THREAD

**Issue by tpchinoda-ibm** [ibm-cloud-architecture/refarch-cloudnative#10]
This could be either in this root repository component under prerequisites or in the mysql project repository. Without having this IBM Containers CLI Plugin installed step 6 in the mysql project instructions, under "Setup Inventory Database in IBM Bluemix container", fails when it has not been previously installed in the local environment.

Something like the below should suffice:

"**Install the IBM Containers CLI Plugin**
In order complete the sections of this tutorial that require using the IBM Containers CLI the plugin needs to be installed in your loval environment. To install it please refer instructions at the following link:

https://console.ng.bluemix.net/docs/containers/container_cli_cfic.html"
Thanks,

**Comment by gangchen03** [comment]
Thanks for reporting this issue, will address it.

**Comment by gangchen03** [comment]
Issue has been addressed, updated the instruction, change is in r1defect branch, will merge to master later this week.
